services:
  core:
    image: app.git.valerii.cc/valerii/tmp-python-service:latest
    container_name: core
    restart: unless-stopped
    tty: false
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
